name: md_house

on:
  push:
  schedule:
  - cron: "0 8-18 * * *" # runs every hour from 8 am - 6 pm

jobs:
  autoscrape:
    env:
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      DOC_URL: ${{ secrets.DOC_URL }}


    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: setup firefox 
        uses: browser-actions/setup-firefox@v1
      - name: Firefox version
        run: firefox --version
      - name: Install packages
        run: |
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("RSelenium")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("furrr")'
          R -e 'install.packages("janitor")'
          R -e 'install.packages("googlesheets4")'
          R -e 'install.packages("slackr")'
      - name: scrape - r
        run: Rscript md_leg_scraper.R
      - name: fetch
        run: git fetch
      - name: pull
        run: git pull
      - name: add
        run: git add --all
      - name: commit
        run: git commit

