name: md_house

on:
  push:
  schedule:
  - cron: "0 8-18 * * *" # runs every hour from 8 am - 6 pm

jobs:
  autoscrape:
    env:
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      DOC_URL: ${{ secrets.DOC_URL }}

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: browser-actions/setup-geckodriver@latest
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version
      - uses: browser-actions/setup-firefox@latest 
      - run: firefox --version 
      - name: Install RSelenium package 
        run: Rscript -e 'install.packages(c("wdman", "httr", "binman", "curl", "RSelenium"))'
        
      - name: Install packages
        run: |
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("curl")'
          R -e 'install.packages("gargle")'
          R -e 'install.packages("httr")'
          R -e 'install.packages("googledrive")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("furrr")'
          R -e 'install.packages("janitor")'
          R -e 'install.packages("googlesheets4")'
          R -e 'install.packages("slackr")'
          R -e 'install.packages("remotes")'
          
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/R/site-library
          key: R-site-library-${{ hashFiles('**/DESCRIPTION') }}
      - name: scrape - r
        run: Rscript md_leg_scraper.R
      - name: fetch
        run: git fetch
      - name: pull
        run: git pull
      - name: add
        run: git add --all
      - name: commit
        run: git commit -m "auto update of scraped data"
      - name: push
        run: git push
